builds:
  - id: peridot
    main: .
    binary: peridot
    ldflags:
      - "-s -w"
    flags:
      - "--trimpath"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
archives:
  -
    format: binary
    name_template: "{{ .Binary}}-{{ .Os }}-{{ .Arch }}"
release:
  prerelease: auto
  github:
    owner: liamg
    name: peridot

dockers:
  - goos: linux
    goarch: amd64
    ids:
    - peridot
    dockerfile: Dockerfile
    skip_push: auto
    image_templates:
    - "ghcr.io/liamg/{{ .ProjectName }}:{{ .Tag }}"
    - "ghcr.io/liamg/{{ .ProjectName }}:latest"
  